export const PASSWORD_RESET="PASSWORD_RESET";
export const ADD_TIME_RECORD="ADD_TIME_RECORD";
export const EDIT_TIME_RECORD="EDIT_TIME_RECORD";
export const DELETE_TIME_RECORD="DELETE_TIME_RECORD";
export const ERROR_ALERT="ERROR_ALERT";